definitions:
  main.ErrorResponse:
    properties:
      error:
        type: string
    type: object
  main.Message:
    properties:
      Args:
        example: '[''000000000019d6689c085ae165831e934ff763ae46a2a6c172b3f1'', ''bitcoin
          first block is here'']'
        type: string
      PassWord:
        example: "123"
        type: string
    type: object
  main.PutSuccessResponse:
    properties:
      message:
        type: string
      playload:
        type: string
    type: object
info:
  contact: {}
paths:
  /get:
    post:
      consumes:
      - application/json
      description: 从 Fabric blockchain 获取数据
      parameters:
      - description: 请求参数
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/main.Message'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.PutSuccessResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/main.ErrorResponse'
        "502":
          description: Bad Gateway
          schema:
            $ref: '#/definitions/main.ErrorResponse'
      summary: 数据查询
  /getfile/{filename}:
    get:
      consumes:
      - application/json
      description: 从服务器下载指定文件
      parameters:
      - description: 要下载的文件名
        in: path
        name: filename
        required: true
        type: string
      produces:
      - application/octet-stream
      responses:
        "200":
          description: 文件流
          schema:
            type: file
        "404":
          description: 文件未找到
          schema:
            type: string
      summary: 下载文件
  /put:
    post:
      consumes:
      - application/json
      description: 将数据上链到Fabric
      parameters:
      - description: 请求参数
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/main.Message'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.PutSuccessResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/main.ErrorResponse'
        "502":
          description: Bad Gateway
          schema:
            $ref: '#/definitions/main.ErrorResponse'
      summary: 将数据上链
  /putfile:
    post:
      consumes:
      - multipart/form-data
      description: 从客户端上传文件到服务器并将文件存储到本地和区块链中
      parameters:
      - description: 文件
        in: formData
        name: file
        required: true
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: 文件上传成功
          schema:
            type: string
        "400":
          description: 请求错误
          schema:
            type: string
        "500":
          description: 服务器内部错误
          schema:
            type: string
      summary: 上传文件
swagger: "2.0"
